src/game/MapPersistentStateMgr.cpp
DungeonPersistentState::UnbindThisState calls Player::UnbindInstance
Which calls DungeonPersistentState::RemovePlayer
Which calls MapPersistentState::UnloadIfEmpty
Which calls MapPersistentStateManager::RemovePersistentState.
MapPersistentStateManager::RemovePersistentState modifies the m_instanceSaveByInstanceId collection being iterated over in MapPersistentStateManager::_ResetOrWarnAll
Though perhaps it is cleaner to update the iterator upon removal, it would be a much more drastic change, and I think ultimately not as clean.
I am submitting this via pull request to give people an opportunity to review it.
=> Fixed crash in instance resetting code in MapPersistentStateManager::_ResetOrWarnAll

src/scriptdev2/scripts/eastern_kingdoms/molten_core/boss_garr.cpp, src/scriptdev2/scripts/eastern_kingdoms/molten_core/boss_golemagg.cpp, src/scriptdev2/scripts/northrend/naxxramas/boss_anubrekhan.cpp, src/scriptdev2/scripts/northrend/naxxramas/boss_gluth.cpp, src/scriptdev2/scripts/northrend/naxxramas/boss_maexxna.cpp
MC - Firesworn - Thrash & Immolate
MC - Golemagg - Double Attack
MC - Core Rager - Thrash
Naxxramas - Anub'Rekhan - Double Attack
Naxxramas - Maexxna - Double Attack
Naxxramas - Gluth - Double Attack
=> MC & Naxxramas - Missing Spells

src/game/ScriptMgr.cpp, src/game/ScriptMgr.h
=> Implement SCRIPT_COMMAND_UPDATE_TEMPLATE

AUTHORS.md, src/game/Chat.h, src/game/Creature.cpp, src/game/Group.cpp, src/game/Level1.cpp, src/game/Level3.cpp, src/game/Pet.cpp, src/game/Pet.h, src/game/PetAI.cpp, src/game/PetHandler.cpp, src/game/Player.cpp, src/game/Player.h, src/game/Spell.cpp, src/game/SpellAuras.cpp, src/game/SpellEffects.cpp, src/game/TemporarySummon.cpp, src/game/Unit.cpp, src/game/Unit.h
~~And this is where my support reaches its end; i do not have any interest in wow emulation beyond wrath~~ Who am I kidding, there's going to be a cata port. I may even make a wod port -.-
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cmangos/mangos-wotlk/192)
=> Pet patch porting 1.0

src/game/SpellEffects.cpp, src/game/SpellMgr.cpp
=> q.10657 script

dep/include/g3dlite/G3D/System.h
=> Fix FreeBSD build

sql/base/mangos.sql, sql/updates/mangos/areatriggerteleport_condition.sql, sql/updates/mangos/questConditions.sql, sql/updates/mangos/trainer_conditon_id.sql, src/game/Creature.h, src/game/MiscHandler.cpp, src/game/NPCHandler.cpp, src/game/ObjectMgr.cpp, src/game/ObjectMgr.h, src/game/Player.cpp, src/game/Player.h, src/game/QuestDef.cpp, src/game/QuestDef.h, src/game/QuestHandler.cpp, src/game/Spell.cpp, src/game/SpellAuras.cpp, src/game/SpellAuras.h, src/game/SpellMgr.cpp, src/game/SpellMgr.h, src/game/Unit.cpp, src/game/UnitAuraProcHandler.cpp, src/game/World.cpp
=> Prport of recent TBC changes

sql/scriptdev2/scriptdev2.sql, src/scriptdev2/scripts/northrend/howling_fjord.cpp
Quest redone using DbScripts and Acid.
Source:
https://github.com/cmangos/wotlk-db/commit/18bb0548eb8e12b6b31d802fc596b68faab586ba
=> Script Removed for quest 11300

src/game/AI/ScriptDevAI/scripts/northrend/ruby_sanctum/boss_halion.cpp
Twilight Halion should remove aura on death too.
=> Add Halion remove phase aura on evade and death.

sql/scriptdev2/scriptdev2.sql, src/game/AI/ScriptDevAI/scripts/world/world_map_scripts.cpp, src/game/AI/ScriptDevAI/scripts/world/world_map_scripts.h
- yells added to existing ones
- horn sound added to all Wotlk Transports
Thx to @Phatcat for help
=> WOTLK Zeppelin Masters updated

src/game/AI/ScriptDevAI/scripts/northrend/gundrak/boss_colossus.cpp, src/game/AI/ScriptDevAI/scripts/northrend/utgarde_keep/utgarde_pinnacle/boss_gortok.cpp
UNIT_FLAG_IMMUNE_TO_PLAYER correctly removed during boss fight
Part of:
https://github.com/cmangos/wotlk-db/issues/230
Closes:
https://github.com/cmangos/wotlk-db/issues/270
=> Fix Drakkari Colossus & Gortok Palehoof

src/game/Spells/SpellEffects.cpp
Author:  ariel
Source: TrinityCore
https://github.com/TrinityCore/TrinityCore/commit/0d91ccf6bd066d64283e4b31fc005584682c4107
=> Abyssal Shatter should have a chance to skill up

sql/scriptdev2/spell.sql, src/game/AI/ScriptDevAI/scripts/northrend/dragonblight.cpp
Related to q.11983 'Blood Oath of the Horde'
thx to @killerwife for help
=> SD2 support for spell 47028

doc/script_commands.txt, src/game/DBScripts/ScriptMgr.cpp
Allow to change targets "Z" position.
Req in some WotlK Quests like this one:
https://www.youtube.com/watch?v=zbRcYOd0Kkw
=> New option added for DBScript command-3

src/game/Spells/SpellMgr.cpp
Allow to see summon visual effect
Req. for:
https://github.com/cmangos/wotlk-db/commit/94f78ed4f19d8d4fe070dd3e79841640e009b780
WoTLK FIX Only.
=> Add stack rules for Warlock and Paladin Mount Spells

sql/scriptdev2/spell.sql, src/game/AI/ScriptDevAI/scripts/northrend/dragonblight.cpp
Spell: Army of the Dead - fixed
Thx @killerwife for help
=> Spell: Targets check for 49099

src/game/AI/ScriptDevAI/scripts/eastern_kingdoms/stormwind_city.cpp, src/game/AI/ScriptDevAI/scripts/northrend/dragonblight.cpp, src/game/Spells/SpellMgr.cpp
- script fixed and moved to stormwind.cpp
- allow auras work together
=> Post-WrathGate Portals - improvements

sql/scriptdev2/spell.sql, src/game/AI/ScriptDevAI/scripts/northrend/dragonblight.cpp
Allow to cast it only with aura 47447
Thx to: @killerwife
=> SD2 support for spell 47435

sql/scriptdev2/spell.sql, src/game/AI/ScriptDevAI/scripts/northrend/dragonblight.cpp
=> SD2 support for spell 47431

src/game/Spells/SpellMgr.cpp
Ref:
https://github.com/cmangos/issues/issues/2241
=> Add stack rules for Polymorph spells

sql/scriptdev2/spell.sql, src/game/AI/ScriptDevAI/scripts/northrend/dragonblight.cpp
Allow to cast it only with aura 43671
Tested
=> SD2 support for spell 48397

src/game/Spells/Spell.cpp
=> Spell: 49554 SpellRange fixed

sql/scriptdev2/spell.sql, src/game/AI/ScriptDevAI/scripts/northrend/dragonblight.cpp
no more self harm
Part of:
https://github.com/cmangos/wotlk-db/issues/329
=> spell: 47938 targets corrected

sql/scriptdev2/spell.sql, src/game/AI/ScriptDevAI/scripts/world/spell_scripts.cpp
Shouldn't trigger if Player > 35% HP
=> Spell: HP check added for 52419

sql/scriptdev2/spell.sql
Ref:
https://github.com/cmangos/wotlk-db/issues/339
=> Spell: 42672 Script assigned

sql/scriptdev2/spell.sql, src/game/AI/ScriptDevAI/scripts/northrend/grizzly_hills.cpp
Should target only 1 creature
Part of:
https://github.com/cmangos/wotlk-db/issues/258
=> Spell: 49546 Targets corrected

sql/scriptdev2/spell.sql, src/game/AI/ScriptDevAI/scripts/northrend/grizzly_hills.cpp
=> Spell: 50471 Script added

src/game/AI/ScriptDevAI/scripts/world/spell_scripts.cpp
=> Spell: Removed Script from 47005

.gitignore, src/framework/Platform/CompilerDefs.h, src/shared/Database/Database.cpp, src/shared/Database/Database.h, src/shared/Database/Field.cpp, src/shared/Database/QueryResult.h, src/shared/Database/SQLStorage.cpp, src/shared/Database/SQLStorage.h, src/shared/Database/SqlDelayThread.h, src/shared/Database/SqlOperations.cpp, src/shared/Metric/Measurement.cpp, src/shared/Network/Listener.hpp, src/shared/Network/NetworkThread.cpp, src/shared/ProgressBar.h, src/shared/ServiceWin32.cpp, src/shared/ServiceWin32.h
Just some small changes from vanilla/tbc branches that seem to be lost in merging. This basically brings framework library to equal state in classic/tbc/wotlk and syncs up shared library as much as possible.
- None
- None
- None
=> Backported missing changes from vanilla/tbc

src/game/PlayerBot/Base/PlayerbotAI.cpp
Fixes build error that occurs when wotlk is compiled with PlayerBots enabled
- None
- None
- None
=> Updated KilledMonster() call to use correct params

src/game/PlayerBot/Base/PlayerbotAI.cpp
=> fix compilation due to function rename

sql/scriptdev2/scriptdev2.sql
Fixes an issue with importing of the scriptdev2.sql, there was an unexpected ; in there.
You can validate it by trying to load the scriptdev2.sql file from before and after this request.
=> Fixed unexpected ; on 4738. Changed it into a ,

src/game/AI/ScriptDevAI/scripts/northrend/ulduar/halls_of_stone/halls_of_stoneScripts.cpp, src/game/Battlefield/BattlefieldWG.cpp, src/game/MotionGenerators/MovementHandler.cpp, src/game/OutdoorPvP/OutdoorPvPEP.cpp, src/game/OutdoorPvP/OutdoorPvPNA.cpp, src/game/OutdoorPvP/OutdoorPvPZM.cpp
This removes all current clang compiler warnings
- `make clean && make -j32`
=> Fix compiler warnings

src/game/Entities/Transports.cpp
Just a refactor to closer match client calculations
- None
- None
=> Transports: Use already existing interpolation functions instead of creating our own

src/game/Spells/SpellMgr.h
fix issue https://github.com/cmangos/issues/issues/2965
=> fix aura 8733 stacking with itself

sql/scriptdev2/spell.sql, src/game/AI/ScriptDevAI/scripts/northrend/zuldrak.cpp
=> spell Fix : 55368 - Summon Stefan

src/game/Maps/GridMap.cpp
This PR improves the readability and clarity of error messages related to vmap and map files.
=> Maps: Improve error messages for missing or incorrect (v)map files

src/game/Spells/SpellEffects.cpp
=> Spell: Script removed for spell 51333

src/game/Spells/SpellEffects.cpp
=> Spell: Script removed for spell 51276

src/game/BattleGround/BattleGroundMgr.cpp
Fixes startup crash on sensitive systems. ;-)
- None
- None
- None
=> Fix wrong field index in BattleGroundMgr::CreateInitialBattleGrounds

sql/scriptdev2/spell.sql, src/game/AI/ScriptDevAI/scripts/kalimdor/feralas.cpp
Updated in 3.2 patch
- diff name
- diff targets
- cooldown reduced to 1000
=> Feralas: Spell 11886 Updated for 3.2.x

sql/scriptdev2/scriptdev2.sql, src/game/AI/ScriptDevAI/scripts/northrend/zuldrak.cpp
handled by DB
wasnt complete anyway
=> [Sd2] ZulDrak: Removed Script for Gurgthock

sql/scriptdev2/spell.sql, src/game/Spells/Scripts/Scripting/ClassScripts/Paladin.cpp
This PR adds a Spell Script for the Ardent Defender spell.
***It is entirely untested***
- fixes https://github.com/cmangos/issues/issues/3207
- Create Paladin
- Skill Ardent Defender in Talent Tree
- Get hit
=> Paladin: Add Ardent Defender Spellscript

src/game/AI/ScriptDevAI/scripts/northrend/storm_peaks.cpp
This PR adds scripting for the "Spy Hunter" daily quest for the Sons of Hodir
```sql
DELETE FROM creatures WHERE id=30222;
UPDATE creature_template SET MinLevel=79,MaxLevel=80 WHERE entry=30219;
UPDATE creature_template SET ScriptName="npc_ethereal_frostworg" WHERE entry=30219;
UPDATE creature_template SET SpeedRun=1 WHERE entry=30219;
UPDATE broadcast_text SET ChatTypeID=2 WHERE id BETWEEN 30909 AND 30915;
UPDATE broadcast_text SET EmoteID1=53,SoundEntriesID1=9036 WHERE id=30915;
UPDATE spell_template SET DurationIndex=21 WHERE id=56313;
INSERT INTO gameobject VALUES (9000297, 193993, 571, 1, 4, 7161.85, -2229.08, 759.174, 1.01, 0, 0, 0.881198, 0.472748, 25, 25, 255, 1);
```
=> Add 'Spy Hunter' Hodir Daily Script

src/mangosd/CMakeLists.txt, src/realmd/CMakeLists.txt, src/shared/CMakeLists.txt, src/shared/Platform/WheatyExceptionReport.cpp
Wheaty Exception Report was not outputting files on crash after repository reorganization.
Crash server before applying, no file output
- None
Crash server, you get a report now.
=> Fix Wheaty not outputting dumps

src/game/Spells/Spell.h
This PR fixes spells no longer chaining since implementing the chain immunity setting.
- closes https://github.com/cmangos/issues/issues/3301
- Cast Multishot on a group of enemies
=> Fix spell chaining

sql/scriptdev2/scriptdev2.sql, src/game/AI/ScriptDevAI/scripts/world/spell_scripts.cpp
handled in DB
Part of:
https://github.com/cmangos/issues/issues/3228
=> SD2: Removed Script for Q. Curing the Sick

src/game/BattleGround/BattleGround.cpp
This PR fixes the wrong playercount being displayed in Arena
=> Arena: Fix playercount worldstate

src/game/AI/ScriptDevAI/scripts/world/world_map_scripts.cpp
Support of arrival /departure events added
=> Sd2: Zeppelin Transport Scripts

src/game/Entities/Player.cpp
This PR ensures that Cooldowns applied to vehicles are visible to players entering the vehicle
=> Vehicle: Ensure vehicle cooldowns are visible

src/game/AI/ScriptDevAI/base/BossAI.cpp, src/game/AI/ScriptDevAI/base/BossAI.h
This PR moves the opening and closing of encounter doors out of the instance script into the BossAI script and adds timers. Maybe the timers should also be custom but I don't know how the system actually works so for now it's static.
=> BossAI: Add automatic closing and opening of entrance and exit doors with delay

src/game/AI/ScriptDevAI/scripts/northrend/sholazar_basin.cpp
summon should get Players lvl.
=> SD2: Spell Fix for 51759

src/game/AI/ScriptDevAI/scripts/world/areatrigger_scripts.cpp
=> Areatrigger for quest 12575

sql/scriptdev2/scriptdev2.sql, src/game/AI/ScriptDevAI/scripts/northrend/world_northrend.cpp
=> Northrend/Borean: Add weather setting to q.11961

src/game/Entities/Vehicle.cpp
This PR fixes invalid coordinates being used for when no CreatureModels are loaded.
=> Vehicles: Fix invalid coordinates

src/game/Entities/Player.cpp, src/game/Entities/Player.h, src/game/Entities/Unit.cpp, src/game/Entities/Unit.h, src/game/Entities/Vehicle.cpp
This PR ensures that vehicle attachments that have a higher visibility range than the vehicle they're attached to don't appear before the vehicle and thus fall to the ground and appear to not be attached clientside.
=> Vehicles: Ensure vehicle attachments stay attached

src/game/Spells/Spell.cpp
This PR fixes an artificial delay in the damage calculation of a projectile.
- Get into a vehicle that can shoot projectiles
- Shoot a projectile at a distant target
- Observe the time it takes for the damage to be applied before and after the patch
=> Ulduar: Fix Damage calculation delay on projectiles

sql/base/dbc/cmangos_fixes/Spell.sql
This PR adds the serverside spell "Consumption" for the XT-002 encounter
=> Ulduar: Add serverside spell for XT-002

src/game/BattleGround/BattleGround.cpp, src/game/Chat/Level3.cpp, src/shared/Database/DatabaseEnv.h, src/shared/Database/DatabaseSqlite.cpp
fix for few statements I missed
=> SQLite: Fix incompatible sql statements

src/game/Entities/DynamicObject.cpp, src/game/Entities/DynamicObject.h, src/game/Grids/GridNotifiersImpl.h, src/game/Spells/Scripts/SpellScript.h
This PR allows for checking for secondary targets in an AuraScript
=> Spells: Allow secondary target checking for persistent area auras

sql/scriptdev2/spell.sql
- fixes https://github.com/cmangos/issues/issues/3650
=> SQL: Fix Merge error

src/game/AI/BaseAI/CreatureAI.h, src/game/AI/BaseAI/UnitAI.h, src/game/AI/ScriptDevAI/scripts/outland/auchindoun/shadow_labyrinth/shadow_labyrinth.h, src/game/AI/ScriptDevAI/scripts/world/spell_scripts_wotlk.cpp, src/game/Spells/Spell.h
This PR fixes an error that caused WotLK not to build when PCH was disabled.
- [CI](https://github.com/cmangos/mangos-wotlk/actions/runs/8865994482/job/24342880247)
=> Fix WotLK Non-PCH build

doc/EventAI.txt, src/game/AI/BaseAI/UnitAI.h, src/game/AI/EventAI/CreatureEventAI.cpp, src/game/AI/EventAI/CreatureEventAI.h, src/game/Entities/Vehicle.cpp
I have no idea what I'm doing.
=> Scripts: Implement EAI vehicle hooks

.github/workflows/macos.yml
Also update Platform Version for Boost dependency
=> CI: Update Platform Version for Boost

sql/scriptdev2/spell.sql, src/game/AI/ScriptDevAI/scripts/northrend/icecrown.cpp
=> Sd2: Spell 57413

src/game/AI/ScriptDevAI/scripts/northrend/howling_fjord.cpp
=> Spell: 42793 corrected

sql/scriptdev2/spell.sql, src/game/AI/ScriptDevAI/scripts/northrend/icecrown.cpp
=> Spell: 61171 - Burning

sql/scriptdev2/spell.sql, src/game/AI/ScriptDevAI/scripts/northrend/icecrown.cpp
=> Spell: 59288 - Infra-Green Shield

sql/scriptdev2/scriptdev2.sql, src/game/AI/ScriptDevAI/scripts/kalimdor/azshara.cpp
Gossip moved to DB
Part of:
https://github.com/cmangos/wotlk-db/commit/057730932827ad3961c794b201ab09184223f4f3
=> SD2: Loramus Thalipedes 7783 update

sql/scriptdev2/scriptdev2.sql, src/game/AI/ScriptDevAI/scripts/kalimdor/tanaris.cpp
Gossip moved to DB
Part of:
https://github.com/cmangos/wotlk-db/commit/51f6682b899e43b50a6eef07d9541ffaccc3f82d
=> SD2: Stone Watcher of Norgannon 7918

src/game/Entities/GossipDef.cpp
This PR fixes Auto-Accepted quests not also being auto-completed, if they are auto-complete-able.
- None
- fixes https://github.com/cmangos/wotlk-db/issues/1322
- Create new Human
- Talk to NPC right in front of you
- Quest can now be handed in
=> Quest: Ensure that instant complete quests are completed

src/game/Globals/GraveyardManager.cpp
This PR ensures that if no GY can be found for a given character, Westfall is chosen.
=> SafeLoc: Implement Westfall GY as fallback graveyard

sql/scriptdev2/spell.sql, src/game/AI/ScriptDevAI/scripts/northrend/icecrown.cpp
=> Spell: 25730 - Find the Ancient Hero - Fixed

src/game/Entities/Creature.cpp, src/game/Entities/Creature.h, src/game/Entities/Unit.cpp, src/game/Entities/Unit.h
This PR implements CreatureStaticFlags2::IGNORE_SANCTUARY
=> StaticFlags: Implement IGNORE_SANCTUARY

src/game/Entities/CreatureSettings.cpp
This PR implements CreatureStaticFlags4::NO_BIRTH_ANIM
=> StaticFlags: Implement NO_BIRTH_ANIM

src/game/Entities/Creature.cpp
This PR implements the CreatureStaticFlags3::FOREVER_CORPSE_DURATION static flag
=> StaticFlags: Implement FOREVER_CORPSE_DURATION

src/game/Entities/CreatureSettings.cpp
This PR implements CreatureStaticFlags3::SPELL_CLICK_FOR_PARTY_ONLY
=> StaticFlags: Implement SPELL_CLICK_FOR_PARTY_ONLY

sql/scriptdev2/spell.sql, src/game/AI/ScriptDevAI/scripts/northrend/icecrown.cpp
=> Icecrown: Target corrected for Spell 57853

sql/scriptdev2/spell.sql, src/game/AI/ScriptDevAI/scripts/northrend/icecrown.cpp
=> Icecrown: Spell 58569 Scripted

sql/scriptdev2/scriptdev2.sql, src/game/AI/ScriptDevAI/scripts/northrend/icecrown.cpp
=> Icecrown: Bloodstained Stone

src/realmd/CMakeLists.txt
This PR should fix building on Apple silicon machines
=> Build: Fix linking on apple silicon

src/game/Maps/Map.cpp
This PR fixes playerbots build for the latest login order changes from kw
=> PlayerBot: Fix build with new login order

src/game/AI/ScriptDevAI/scripts/northrend/icecrown.cpp
summon must get Players faction
=> Spell: Icecrown - 63791 63792 update

src/game/Maps/Map.cpp
A small fix for the playerbot module integration.
=> Playerbot: Compile fix UpdateVisibility only for real players
