cmangos/mangos-wotlk

.travis.yml, dep/src/g3dlite/uint128.cpp, src/game/vmap/RegularGrid.h
The clang build on travis has been broken (or rather: replaced by another
GCC build) since commit 7b68f38 because the install part always set GCC as
the compiler. Using built-in travis addons to install the sources fixes
this problem.
=> Fix travis clang build

src/scriptdev2/scripts/kalimdor/temple_of_ahnqiraj/boss_skeram.cpp
As of now, if you engage The Prophet Skeram in AQ40 he instakills you by spamming Earth Shock, because the spell gets cast on each update call of the ai script.
This commit fixes the spell spam and also corrects the spell mechanic itself: Skeram only uses Earth Shock if the the victim is not auto attacking him *or* Skeram cannot reach his current victim.
I went to live for testing the mechanic and found out that contrary to wowwiki ("once every second") he instead casts it every 1.2 seconds. Feel free to comment on / improve the change.
Edit: Removed a weird initial commit from history.
In the updated commit Skeram no longer chooses his Earth Shock target randomly but the victim itself (as stated on wowwiki). I also dewrapped the timer so it ticks regardless whether he would be able cast …
=> Fix Skeram Earth Shock

src/game/MiscHandler.cpp
Inspect handler should not silently (server-side only) change player's current selection. This behaviour leads to unwanted side-effects such as summons landing on wrong group members. Its intended for inspect target and real player target to be separate, as many addons rely on background inspect queries to function properly.
=> Fix for the so-called "target bug"

sql/scriptdev2/scriptdev2.sql
•InstallFullDB.sh ... adds scriptdev2.sql after all DB updates, so
using DB update for scripted_areatriggers is not a good option. - Fixed
•Also - Cleanup for /* AREATRIGGER */ - we dont need to use
delete/insert if TRUNCATE scripted_areatrigger is used before.
•Cala;s update for UBRS implemented
=> Add Areatrigger 171 into ScriptDev2

src/game/AI/ScriptDevAI/scripts/northrend/howling_fjord.cpp
Players should be able to pick up frog without buying second item first..
=> Q.11476 wrong check removed

src/game/PlayerBot/Base/PlayerbotAI.cpp
Fixes Issue 1498.
Added LOOT_TYPE_OWNER items to list that is allowed.
=> allow PlayerBot to pick up quest items

src/game/Spells/Spell.cpp, src/game/Spells/Spell.h, src/game/Spells/SpellEffects.cpp
See: https://github.com/cmangos/mangos-tbc/pull/288
This is modified from the TBC version to account for any Healthstone (unique item no matter the rank).
=> sync: Avoid using Soul Stones when you already have Healthstone

src/game/Spells/SpellEffects.cpp
Missed bit of change from porting from classic/tbc to wotlk
Change can be seen here; https://github.com/cmangos/mangos-classic/pull/124/commits/47274eb44943a92e1d60a0268655dd11b6b1183c#diff-6e2ad27531ee8eb7bafce8a41909816aR4730
and this is the wotlk commit which is missing this change; https://github.com/cmangos/mangos-wotlk/pull/192/commits/5eb9809fc08991ebf8dbb0f8d9e755af873466ce
relates to https://github.com/cmangos/issues/issues/869 and https://github.com/cmangos/issues/issues/107 but I'm not sure it actually solves it (even though it's working as intended on classic and tbc, perhaps wotlk is missing something else, something more)
=> Oversight in porting (from 2016)

src/game/Spells/SpellMgr.cpp
Players must be able to hold both auras in same time...
=> Add stack rules for 2 Dragonblight spells

sql/scriptdev2/scriptdev2.sql, src/game/AI/ScriptDevAI/scripts/northrend/dragonblight.cpp, src/game/Spells/SpellMgr.cpp
See Wintergarde Invisibility Type B - allow to see npcs
See Wintergarde Invisibility Type C - allow to see gobject
Req. for q.12282 'Imprints on the Past'
=> Add stack rules for Wintergarde Invisibility Spells

sql/scriptdev2/spell.sql, src/game/AI/ScriptDevAI/scripts/eastern_kingdoms/western_plaguelands.cpp
Radius corrected for both effects
- eff0 must be 0
- eff1 set to 10
Will prevent charges wastege in case of summoned object out of source radius. (spellfocus)
=> Spell: 17016 Radius corrected

src/game/AI/ScriptDevAI/scripts/northrend/grizzly_hills.cpp
she must despawn on quests complete instead of running back to spawn point
=> SD2: Script update for NPC Emilly

src/game/Loot/LootMgr.cpp
I created an additional disenchanting case for one of the Loot() constructors. This allows the loot object to have it's owner set when creating the temporary loot object for disenchanting rolls.
- None
- Fixes #2463 https://github.com/cmangos/issues/issues/2463
- Be in a group with an enchanter
- Roll disenchant on the item and win the roll
=> Fixed disenchantment rolls not giving out items

src/game/Entities/Unit.h
Without a WotLK client or server I cannot be 100% sure, but this virtual function may be responsible for players currently being invisible to other players or to hostile NPCs (until they have engaged said hostile NPCs in combat on their own)
See link for reasoning and surrounding commit: https://github.com/cmangos/mangos-wotlk/commit/ffe9d0ff63a6189825ab021aded56a44c40eb9f6#r64471224
- Per request
- Discord Support Request
- Log in with 2 separate accounts in the same location and check visibility of the other account
=> Keep Units visible default unless flag is set

src/game/Entities/Unit.cpp, src/game/Entities/Unit.h
In WotLK, the field TargetState in SMSG_ATTACKERSTATEUPDATE is one byte long.
Sending it to client as 4-byte long will cause a bug in the combat log: whenever someone blocks an attack, the blocked amount overflows.
Before:
After:
- [WowPacketParser](https://github.com/TrinityCore/WowPacketParser/commit/5e753e400839dc12409a61580694ee87f64adbf2#diff-5f9cf07fe0e791d35ad0d19bb9f55b4211d424f5e218f7e65968ddbf56e708cfR73) treats is as byte.
- None
Using a character that can block and equipping a shield, get attacked by a mob until you block (easier if you use a Warrior with Shield Block for 100% block chance).
=> Fix size of TargetState in SMSG_ATTACKERSTATEUPDATE packet

src/game/PlayerBot/Base/PlayerbotAI.cpp
Fixes compilation errors when building CMangos-Wotlk with Playerbot enabled, due to the recent refactoring of the spell attributes enum.
- None
- None
- None
=> Fix compile errors on PlayerBot

src/game/Spells/UnitAuraProcHandler.cpp
This PR ensures that Seal of Vengeance and Seal of Corruption correctly apply stacks on melee white-hits
- fixes https://github.com/cmangos/issues/issues/2824
=> Paladin: Fix Seal of Vengeance/Corruption Stack application

src/game/AI/ScriptDevAI/base/TimerAI.h
This PR allows for std::chrono_literals to be used when manipulating CombatAI timers
(instead of `8 * MINUTE * IN_MILLISECONDS` you can now just write `8min`)
=> CombatAI: Allow manipulating timers with Chrono literals

src/game/Spells/SpellEffects.cpp
This PR ensures that the "Call of the ..." Spells cannot be used to circumvent Totem cooldowns.
- fixes https://github.com/cmangos/issues/issues/2800
=> Shaman: Respect Totem cooldowns even when using a Call spell

src/game/AI/ScriptDevAI/base/BossAI.cpp
This PR fixes a typo in the BossAI implementation that can crash the server if no AggroTexts, but some DeathTexts are set
=> BossAI: Fix typo that can lead to crashes

sql/scriptdev2/spell.sql, src/game/Spells/Scripts/Scripting/ClassScripts/Shaman.cpp
This PR makes it so Heroism/Bloodlust isn't cast on characters with the Sated/Exhausted debuff.
There is a minor issue with how it currently works, and that is that when everybody in the group/raid has the sated/exhausted debuff and the shaman uses bloodlust/heroism no sound is being played. I'm not sure if that's how it's supposed to be.
- fixes https://github.com/cmangos/issues/issues/3083
- Create Shaman
- Use `.level 79`
- Use `.learn all_myclass`
- Cast Bloodlust/Heroism from the Enhancement Spellbook
- Use `.cooldown clear`
- Cast Bloodlust/Heroism again
=> Shaman: Don't add heroism/bloodlust on sated targets

src/game/AI/ScriptDevAI/scripts/northrend/ulduar/ulduar/boss_yogg_saron.cpp, src/game/AI/ScriptDevAI/scripts/northrend/ulduar/ulduar/ulduar.cpp, src/game/AI/ScriptDevAI/scripts/northrend/ulduar/ulduar/ulduar.h, src/game/Spells/Scripts/Scripting/ClassScripts/Paladin.cpp
This PR adds a Spell-Script for "Hodir's Protective Gaze"
- [Ensidia World First Yogg-Saron](https://www.youtube.com/watch?v=iatGk4TOlEA)
- fixes https://github.com/cmangos/issues/issues/760
- Begin the Yogg-Saron fight with Hodir's assistance
- Hodir will cast his protective gaze
- take enough damage to die
- protective gaze will activate and prevent death
- the aura will vanish for all players and only reappear 25 seconds later
=> Ulduar: Add Hodir's Protective Gaze Spellscript

src/game/Spells/Scripts/Scripting/ClassScripts/Hunter.cpp
Spell duration can be checked with target as nullptr in some places
For me it happened here https://github.com/cmangos/mangos-wotlk/blob/master/src/game/Spells/Spell.cpp#L3661
=> Fix crash in Wyvern Sting

src/game/Entities/Vehicle.cpp
This PR makes sure that pets are stored correctly when the player enters a vehicle, so that they are re-summoned once the player exits the vehicle.
=> Store pet correctly when entering vehicle

src/game/AuctionHouseBot/AuctionHouseBot.cpp
This PR fixes the gameobject loot loading query for the AH bot. The `state` column was moved to `gameobject_addon`, which currently leads to an SQL error on startup if the AH bot is enabled. I removed the state condition entirely, since the query results (before state migration including the state condition and after the state migration without the state condition) are the same (tested on wotlk-db only).
[- State column was moved to gameobject_addon](https://github.com/cmangos/mangos-wotlk/commit/fb6f93170aaf4219ecc1935f39715ec4e7973994)
- None
1. Enable AH bot
2. When starting the application, the SQL error should not appear anymore
=> AuctionHouseBot: Fix invalid gameobject loot query by removing state condition

src/game/Spells/Scripts/Scripting/ClassScripts/Paladin.cpp
This PR ensures that Ardent Defender can never heal more than the maximum allowed by the talent rank, and never heal less than 0 (do damage?)
=> Spell: Ensure Ardent Defender never heals more than max and never less than 0

contrib/extractor_scripts/ExtractResources.sh
This PR ensures that the extractors can be run properly without requiring them to run through bash by hand.
Parts of the script are not POSIX compliant and thus don't work with /bin/sh
=> Extractors: Change shebang

src/game/BattleGround/BattleGroundWS.cpp
Valid for TBC and WotLK. Classic does not have this mechanic.
`bool IsFlagPickedUp(uint8 teamIdx))` expects to receive an index for `m_flagCarrier`, but a `Team` value was passed instead, causing a crash.
- None
- None
- None
=> Fix crash in BattleGroundWS.cpp due to wrong argument passed to IsFlagPickedUp()

src/game/BattleGround/BattleGroundAV.cpp
This error messed up Alterac Valley reinforcements because it would update only Alliance ones regardless.
- None
- None
- None
=> Fix mistake when updating score in Alterac Valley

src/shared/Database/QueryResultSqlite.cpp
This PR fixes empty integer fields being misinterpreted as empty strings
=> SQLite: Fix null-data handling

src/game/Loot/LootMgr.h
This PR fixes compilation errors for pre-gcc13 users by moving the LootTemplate class declaration in LootMgr.h prior to it's call in the LootStore class.
https://github.com/cmangos/issues/issues/3666
https://github.com/cmangos/issues/issues/3667
https://github.com/cmangos/issues/issues/3666
https://github.com/cmangos/issues/issues/3667
Compile on a pre-gcc13 distrubution.
=> Fix compilation errors

src/game/Anticheat/module/anticheat.conf.dist.in, src/game/Anticheat/module/libanticheat.cpp, src/game/AuctionHouseBot/AuctionHouseBot.cpp, src/mangosd/Main.cpp, src/mangosd/mangosd.conf.dist.in, src/realmd/Main.cpp, src/realmd/realmd.conf.dist.in, src/shared/Config/Config.cpp, src/shared/Config/Config.h
Implement overriding of configuration from the .conf file with environment variables. Environment variables keys are autogenerated based on the keys defined in .conf file. 
Usage example:
```
$ export CM_DATA_DIR=/usr
$ CM_WORLD_SERVER_PORT=8080 ./mangosd
```
- None
- None
- None
=> Config: Implement config override with env vars

src/game/Entities/Unit.cpp
This PR checks if `caster` is nullptr before assuming it can get an ObjectGuid from the object. Consistent with nullptr checks lower down in the function.
- fixes https://github.com/cmangos/issues/issues/3654
- No idea, I haven't been able to reproduce the original issue. Someone on discord has been experiencing the issue however and this seems to have solved it (see backtrace posted in gh issue)
=> Unit: Add nullptr check for caster

dep/g3dlite/System.cpp
This PR removes some deprecated MacOS system calls from the G3D library, as they have been removed entirely in recent versions of MacOS, leading to linker errors.
=> G3D: Extend Support for new MacOS Versions (+Apple Silicon)

src/game/Entities/Unit.cpp, src/game/Spells/SpellMgr.h
- fixes https://github.com/cmangos/issues/issues/3652
- Create Warlock
- Level Warlock to 80
- Learn 47836 and 47813
- Cast them on a target such that one spell replaces the other
=> Spells: Ensure that Corruption and Seed of Corruption are interchangeable

src/game/Entities/Player.cpp
This PR fixes a bug that prevents you from logging in if you logged out on a moving transport.
- None
- None
- `.tele deeprun`
- Wait for a gondola
- step onto the gondola
- wait until it starts moving then log out
- log back in
=> Fix logging in/out on moving transport

.github/workflows/macos.yml
This PR updates the version of the MacOS CI/CD runner from 11 to 12.
See https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
=> CI/CD: Update MacOS version to 12

src/game/AI/ScriptDevAI/scripts/kalimdor/caverns_of_time/hyjal/hyjal.cpp
Adds Death Knight to the Soul Charge color effects for Archimonde in Hyjal Summit.
- Tested on Dragonflight, Soul Charge color spell ID observed in sniff.
- None
- Engage Archimonde in Hyjal with at least two characters, one of which being a Death Knight.
- Allow Archimonde to kill the Death Knight.
- Observe the Soul Charge effect as a result of the death.
=> Add Death Knight assignment for Soul Charge color.

src/game/Entities/GameObject.cpp
This PR ensures that defending a contested but not neutralized/taken base does not count as another base capture.
- fixes https://github.com/cmangos/issues/issues/3726
- Create 2 Characters, 1 Alliance, 1 Horde
- set your characters to level 70
- enable .debug bg
- use the BG auto-join to join an EOTS bg
- use .bg start to start the bg prematurely
- take your alliance character and capture the draenei ruins base (works with any base and any faction, just using this as an example for simplification)
- once the base is fully captured with the bar all the way to the edge walk out of the capture range of the base with your alliance character
- move your horde character to the draenei ruins base and let it capture one or two ticks then move the character out of the capture range of the base …
=> Battleground: Fix EOTS bases being capturable multiple times

src/game/Server/WorldSession.cpp, src/game/Server/WorldSession.h
This PR removes an unused sync timer from WotLK
=> WorldSession: Remove unused sync timer

src/game/Entities/Unit.cpp, src/game/Entities/Unit.h
This PR fixes Manashield not properly absorbing mana and not updating the mana update field for the client.
This PR also deprecates the `ApplyPowerMod` function which is not used anywhere else and should not be used in my opinion
- None
- fixes https://github.com/cmangos/issues/issues/3114
- level mage to level 20
- learn mana shield (1463)
- get into combat with an enemy
- cast mana shield
- watch mana bar
=> Fix Manashield and deprecate ApplyPowerMod

sql/scriptdev2/spell.sql, src/game/AI/ScriptDevAI/scripts/world/item_scripts_wotlk.cpp
This PR adds an implementation for the `Mind Amplification Dish` Engineering thingie.
PR is a draft because I don't have reliable probability numbers, just a very small sample size.
- None
- fixes https://github.com/cmangos/issues/issues/3065
- Learn Spell 67799
- Keep casting spell on enemy humanoids
=> Spell: Add SpellScript for Mind Amplification Dish

src/game/Entities/GossipDef.cpp, src/game/Quests/QuestDef.cpp
This PR allows Quests in the starting zones (Quests with the flag "QUEST_FLAGS_AUTO_ACCEPT") to be automatically accepted.
This PR is for WotLK *only*.
- fixes https://github.com/cmangos/issues/issues/2947
- Create new character
- Talk to the very first quest-giver
=> Quest: Auto-accept quests in starting zone

src/game/AI/ScriptDevAI/scripts/outland/tempest_keep/the_eye/boss_kaelthas.cpp
This PR ensures that Kael'Thas' Flamestrike does not explode immediately so that players have time to run out of the pre-flamestrike visual.
- https://youtu.be/50rC95LSCZE?t=1942
- fixes https://github.com/cmangos/issues/issues/3762
- Do the Kael'Thas encounter and pay attention to flamestrike
=> Spell: Fix Kael'Thas Flamestrike exploding immediately

src/game/Entities/Player.cpp
This PR switches `RewMaxRepValue` and `RewRepFaction` which were for some reason in the incorrect order.
- may be related to https://github.com/cmangos/issues/issues/2818
- may be related to https://github.com/cmangos/issues/issues/2952
=> Reputation: Fix typo  in function call

src/game/Entities/Creature.cpp, src/game/Entities/Creature.h, src/game/Entities/Unit.cpp
This PR ensures that the initial CallAssistance() function will still be executed when called from SetInCombatState() even if GetVictim() is nullptr
=> Creature: Add function to CallAssistance explicitly

src/game/AI/BaseAI/CreatureAI.cpp
This PR implements CreatureStaticFlags4::NO_MELEE_APPROACH
=> StaticFlags: Implement NO_MELEE_APPROACH

src/game/Entities/Creature.cpp, src/game/Entities/Creature.h, src/game/Entities/Unit.cpp, src/game/Entities/Unit.h
This PR implements CreatureStaticFlags4::CANNOT_DAZE
=> StaticFlags: Implement CANNOT_DAZE

src/game/AI/BaseAI/CreatureAI.cpp, src/game/AI/EventAI/CreatureEventAI.cpp
This PR implements CreatureStaticFlags::IGNORE_COMBAT and CreatureStaticFlags2::SPAWN_DEFENSIVE
=> StaticFlags: Implement SPAWN_DEFENSIVE and IGNORE_COMBAT

sql/scriptdev2/scriptdev2.sql
This PR implements the requests of Grz3s of moving data from the DB repo to the Core repo
=> SD2: Add Hodir updates to sd2.sql

src/game/AI/ScriptDevAI/base/guard_ai.cpp
This is a small crash fix which occurs when a guard is killed using a spell cast by a gameobject.
The killer in JustDied of the guardai is filled here: https://github.com/cmangos/mangos-wotlk/blob/2f5d3f41379b0e478883b893daf5eb6c7a87788d/src/game/Spells/SpellAuras.cpp#L8038
Which is filled with nullptr if the caster is a gameObject: https://github.com/cmangos/mangos-wotlk/blob/2f5d3f41379b0e478883b893daf5eb6c7a87788d/src/game/Spells/SpellAuras.cpp#L10126
This results in a crash trying to find the Beneficiary Player of nullptr.
-Make an alliance hunter with immolation trap.
-Go to mulgore and place the trap near a Brave Dawneagle (or other guard near bloodhoof village) killing it.
-The server will crash.
=> -Prevent crash when killing a guard with a gameobject (like a trap)

src/game/MotionGenerators/TargetedMovementGenerator.cpp, src/game/MotionGenerators/TargetedMovementGenerator.h
This PR implements CreatureStaticFlags4::DONT_REPOSITION_IF_MELEE_TARGET_IS_TOO_CLOSE
=> StaticFlags: Implement DONT_REPOSITION_IF_MELEE_TARGET_IS_TOO_CLOSE

src/shared/Util/CodeBench.cpp, src/shared/Util/CodeBench.h
Old Guard Macro already exists in timer code, so can't be re-used.
Imo we should just switch to
```cpp
#pragma once
```
it is supported by every compiler and build system that is even remotely relevant.
Also fixes ambiguous include statement.
=> Fix CodeBench guard macro

src/game/Maps/MapPersistentStateMgr.cpp
This PR fixes an issue where instanceId's are reshuffled on server boot. The shuffling may move a dungeon instance at instance ID 1 which is reserved for ebon hold (alliance version)
When creating new maps the deathknight start map for alliance is always given instanceId= 1 here: https://github.com/cmangos/mangos-wotlk/blob/6a6de7bc8cf4d96684f200d2d67e645a42fea8ee/src/game/Maps/MapManager.cpp#L131
During shuffling of saved instanceids to pack them in the changed code any saved dungeon can be assigned instanceID 1 which results the maps sharing the same ID causing a crash when loading players for the saved dungeon and finding the deathknight start map in saved instances.
Have a character saved to an instance.
Reboot the server and note that the instanceID is repacked to 1.
Activate the …
=> Map: Fixed a crash loading an instanceId 1 which is reserved for ebonhold

CMakeLists.txt, cmake/options.cmake, src/mangosd/mangosd.conf.dist.in
Adds necessary cmake support to use SQLite on Windows
Requires external SQLite library to be built or otherwise accessible through system path. See steps below for building the library manually.
Download source and binary packages from https://www.sqlite.org/download.html
- source example: `sqlite-amalgamation-3470000.zip`
- binary example: `sqlite-dll-win-x64-3470000.zip`
Extract content of both archives to `C:\Program Files\sqlite` (make sure the files are not in any subdirectories)
Open `Developer Command Prompt for VS` as administrator and navigate to `C:\Program Files\sqlite`
Run  `lib /DEF:sqlite3.def /OUT:sqlite3.lib /MACHINE:x64`
Open System Properties, Environment Variables, System Variables and add C:\Program Files\sqlite to PATH
Reboot to make environment variables take effect …
=> Add SQLite support for Windows

src/game/BattleGround/BattleGroundQueue.cpp
This PR fixes a crash when a remove-event is executed for a BG that's a nullptr.
=> BG: Fix crash in queue remove if `bg` is nullptr
